#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Cage

#include "Basic.hpp"

#include "BP_Cage_classes.hpp"
#include "BP_Cage_parameters.hpp"


namespace SDK
{

// Function BP_Cage.BP_Cage_C.OnRep_IsLowering
// (BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::OnRep_IsLowering()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "OnRep_IsLowering");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.CheckCanClose
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::CheckCanClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "CheckCanClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.CanLower
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   CanLower_0                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Cage_C::CanLower(bool* CanLower_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "CanLower");

	Params::BP_Cage_C_CanLower Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CanLower_0 != nullptr)
		*CanLower_0 = Parms.CanLower_0;
}


// Function BP_Cage.BP_Cage_C.OnRep_IsClosed
// (BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::OnRep_IsClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "OnRep_IsClosed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_0__UnloadPier__EventFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_0__UnloadPier__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_0__UnloadPier__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_0__IsUnderwater__EventFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_0__IsUnderwater__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_0__IsUnderwater__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_0__FadeWaterAndLoad__EventFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_0__FadeWaterAndLoad__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_0__FadeWaterAndLoad__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_0__NewTrack_2__EventFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_0__NewTrack_2__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_0__NewTrack_2__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_0__NewTrack_1__EventFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_0__NewTrack_1__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_0__NewTrack_1__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_2__FinishedFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_2__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_2__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_2__UpdateFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_2__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_2__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_3__FinishedFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_3__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_3__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Timeline_3__UpdateFunc
// (BlueprintEvent)

void ABP_Cage_C::Timeline_3__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Timeline_3__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.LowerCage
// (BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::LowerCage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "LowerCage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.BndEvt__BP_Elevator_Hotel_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Cage_C::BndEvt__BP_Elevator_Hotel_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "BndEvt__BP_Elevator_Hotel_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_Cage_C_BndEvt__BP_Elevator_Hotel_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Cage.BP_Cage_C.MC_Shake
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::MC_Shake()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "MC_Shake");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.MC_Ring
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::MC_Ring()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "MC_Ring");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.MC_ElevatorDoors
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::MC_ElevatorDoors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "MC_ElevatorDoors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.CloseDoors
// (BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::CloseDoors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "CloseDoors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.OpenDoors
// (BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::OpenDoors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "OpenDoors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.Reset
// (BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.StartClosing
// (BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::StartClosing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "StartClosing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Cage_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.MC_Fall
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::MC_Fall()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "MC_Fall");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.MC_Impact
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::MC_Impact()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "MC_Impact");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.MC_SetWaterVolume
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::MC_SetWaterVolume()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "MC_SetWaterVolume");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.MC_EnableWater
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::MC_EnableWater()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "MC_EnableWater");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.FadeWater
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::FadeWater()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "FadeWater");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.MC_UnderwaterAmbience
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Cage_C::MC_UnderwaterAmbience()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "MC_UnderwaterAmbience");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cage.BP_Cage_C.ExecuteUbergraph_BP_Cage
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Cage_C::ExecuteUbergraph_BP_Cage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cage_C", "ExecuteUbergraph_BP_Cage");

	Params::BP_Cage_C_ExecuteUbergraph_BP_Cage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

