#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CeilingFan

#include "Basic.hpp"

#include "BP_CeilingFan_classes.hpp"
#include "BP_CeilingFan_parameters.hpp"


namespace SDK
{

// Function BP_CeilingFan.BP_CeilingFan_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_CeilingFan_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CeilingFan_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CeilingFan.BP_CeilingFan_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_CeilingFan_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CeilingFan_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CeilingFan.BP_CeilingFan_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_CeilingFan_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CeilingFan_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CeilingFan.BP_CeilingFan_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CeilingFan_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CeilingFan_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CeilingFan.BP_CeilingFan_C.ExecuteUbergraph_BP_CeilingFan
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CeilingFan_C::ExecuteUbergraph_BP_CeilingFan(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CeilingFan_C", "ExecuteUbergraph_BP_CeilingFan");

	Params::BP_CeilingFan_C_ExecuteUbergraph_BP_CeilingFan Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

