#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DivingGear

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Backrooms_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DivingGear.BP_DivingGear_C
// 0x0078 (0x02C0 - 0x0248)
class ABP_DivingGear_C final : public AInteractableActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0248(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh3;                                       // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x0258(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             StartTransform;                                    // 0x0260(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FTransform                             OffsetTransform;                                   // 0x0290(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_DivingGear(int32 EntryPoint);
	void OnActorUsed(class ACharacter* Character);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DivingGear_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DivingGear_C")
	}
	static class ABP_DivingGear_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DivingGear_C>();
	}
};
DUMPER7_ASSERTS_ABP_DivingGear_C;

}

