#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Doorframe_in_single

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Doorframe_in_single.BP_Doorframe_in_single_C
// 0x0010 (0x0230 - 0x0220)
class BP_Doorframe_in_single::ABP_Doorframe_in_single_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Doorframe_in_single;                               // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Doorframe_in_single.BP_Doorframe_in_single_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Doorframe_in_single_C")
	}
	static class BP_Doorframe_in_single::ABP_Doorframe_in_single_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Doorframe_in_single::ABP_Doorframe_in_single_C>();
	}
};
DUMPER7_ASSERTS_BP_Doorframe_in_single__ABP_Doorframe_in_single_C;

}

