#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Doorframe_out_single_windows

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Doorframe_out_single_windows.BP_Doorframe_out_single_windows_C
// 0x0020 (0x0240 - 0x0220)
class BP_Doorframe_out_single_windows::ABP_Doorframe_out_single_windows_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Windowglass_doorframe_out_B;                       // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Windowglass_doorframe_out_A;                       // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Doorframe_out_single_windows;                      // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Doorframe_out_single_windows.BP_Doorframe_out_single_windows_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Doorframe_out_single_windows_C")
	}
	static class BP_Doorframe_out_single_windows::ABP_Doorframe_out_single_windows_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Doorframe_out_single_windows::ABP_Doorframe_out_single_windows_C>();
	}
};
DUMPER7_ASSERTS_BP_Doorframe_out_single_windows__ABP_Doorframe_out_single_windows_C;

}

