#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Deep_Volume

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Deep_Volume.BP_Deep_Volume_C
// 0x0018 (0x0240 - 0x0228)
class ABP_Deep_Volume_C final : public ATriggerBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AAmbientSound*                          AmbientSound1;                                     // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AAmbientSound*                          AmbientSound2;                                     // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ReceiveActorEndOverlap(class AActor* OtherActor);
	void ExecuteUbergraph_BP_Deep_Volume(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Deep_Volume_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Deep_Volume_C")
	}
	static class ABP_Deep_Volume_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Deep_Volume_C>();
	}
};
DUMPER7_ASSERTS_ABP_Deep_Volume_C;

}

