#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroppedItem_Ball

#include "Basic.hpp"

#include "BP_DroppedItem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DroppedItem_Ball.BP_DroppedItem_Ball_C
// 0x0000 (0x0270 - 0x0270)
class ABP_DroppedItem_Ball_C final : public ABP_DroppedItem_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DroppedItem_Ball_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DroppedItem_Ball_C")
	}
	static class ABP_DroppedItem_Ball_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroppedItem_Ball_C>();
	}
};
DUMPER7_ASSERTS_ABP_DroppedItem_Ball_C;

}

