#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DivingGear

#include "Basic.hpp"

#include "BP_DivingGear_classes.hpp"
#include "BP_DivingGear_parameters.hpp"


namespace SDK
{

// Function BP_DivingGear.BP_DivingGear_C.ExecuteUbergraph_BP_DivingGear
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DivingGear_C::ExecuteUbergraph_BP_DivingGear(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DivingGear_C", "ExecuteUbergraph_BP_DivingGear");

	Params::BP_DivingGear_C_ExecuteUbergraph_BP_DivingGear Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DivingGear.BP_DivingGear_C.OnActorUsed
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DivingGear_C::OnActorUsed(class ACharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DivingGear_C", "OnActorUsed");

	Params::BP_DivingGear_C_OnActorUsed Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}

}

