#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Door_Master

#include "Basic.hpp"

#include "BP_Door_Master_classes.hpp"
#include "BP_Door_Master_parameters.hpp"


namespace SDK
{

// Function BP_Door_Master.BP_Door_Master_C.ExecuteUbergraph_BP_Door_Master
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Door_Master_C::ExecuteUbergraph_BP_Door_Master(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_Master_C", "ExecuteUbergraph_BP_Door_Master");

	Params::BP_Door_Master_C_ExecuteUbergraph_BP_Door_Master Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Door_Master.BP_Door_Master_C.OnUsedNotify
// (Event, Public, BlueprintEvent)

void ABP_Door_Master_C::OnUsedNotify()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_Master_C", "OnUsedNotify");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Door_Master.BP_Door_Master_C.OpenDoor__UpdateFunc
// (BlueprintEvent)

void ABP_Door_Master_C::OpenDoor__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_Master_C", "OpenDoor__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Door_Master.BP_Door_Master_C.OpenDoor__FinishedFunc
// (BlueprintEvent)

void ABP_Door_Master_C::OpenDoor__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Door_Master_C", "OpenDoor__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

