#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Exit_Manager

#include "Basic.hpp"

#include "BP_Exit_Manager_classes.hpp"
#include "BP_Exit_Manager_parameters.hpp"


namespace SDK
{

// Function BP_Exit_Manager.BP_Exit_Manager_C.AddPlayer
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_Exit_Manager_C::AddPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exit_Manager_C", "AddPlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Exit_Manager.BP_Exit_Manager_C.StartChecking
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_Exit_Manager_C::StartChecking()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exit_Manager_C", "StartChecking");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Exit_Manager.BP_Exit_Manager_C.CheckPlayers
// (BlueprintCallable, BlueprintEvent)

void ABP_Exit_Manager_C::CheckPlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exit_Manager_C", "CheckPlayers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Exit_Manager.BP_Exit_Manager_C.ExecuteUbergraph_BP_Exit_Manager
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Exit_Manager_C::ExecuteUbergraph_BP_Exit_Manager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Exit_Manager_C", "ExecuteUbergraph_BP_Exit_Manager");

	Params::BP_Exit_Manager_C_ExecuteUbergraph_BP_Exit_Manager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

