#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Exit_Manager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Exit_Manager.BP_Exit_Manager_C
// 0x0018 (0x0238 - 0x0220)
class ABP_Exit_Manager_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         Players;                                           // 0x0230(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddPlayer();
	void StartChecking();
	void CheckPlayers();
	void ExecuteUbergraph_BP_Exit_Manager(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Exit_Manager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Exit_Manager_C")
	}
	static class ABP_Exit_Manager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Exit_Manager_C>();
	}
};
DUMPER7_ASSERTS_ABP_Exit_Manager_C;

}

