#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Fish_Manager

#include "Basic.hpp"

#include "BP_Fish_Manager_classes.hpp"
#include "BP_Fish_Manager_parameters.hpp"


namespace SDK
{

// Function BP_Fish_Manager.BP_Fish_Manager_C.SpawnFish
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABPCharacter_Demo_C*              Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   CanSpawn                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FVector*                         StartingLoc                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         FrontLocation                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Fish_Manager_C::SpawnFish(class ABPCharacter_Demo_C* Player, bool* CanSpawn, struct FVector* StartingLoc, struct FVector* FrontLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Fish_Manager_C", "SpawnFish");

	Params::BP_Fish_Manager_C_SpawnFish Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);

	if (CanSpawn != nullptr)
		*CanSpawn = Parms.CanSpawn;

	if (StartingLoc != nullptr)
		*StartingLoc = std::move(Parms.StartingLoc);

	if (FrontLocation != nullptr)
		*FrontLocation = std::move(Parms.FrontLocation);
}


// Function BP_Fish_Manager.BP_Fish_Manager_C.Swim__FinishedFunc
// (BlueprintEvent)

void ABP_Fish_Manager_C::Swim__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Fish_Manager_C", "Swim__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Fish_Manager.BP_Fish_Manager_C.Swim__UpdateFunc
// (BlueprintEvent)

void ABP_Fish_Manager_C::Swim__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Fish_Manager_C", "Swim__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Fish_Manager.BP_Fish_Manager_C.Swim__Destroy__EventFunc
// (BlueprintEvent)

void ABP_Fish_Manager_C::Swim__Destroy__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Fish_Manager_C", "Swim__Destroy__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Fish_Manager.BP_Fish_Manager_C.ScarePlayer
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABPCharacter_Demo_C*              Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Fish_Manager_C::ScarePlayer(class ABPCharacter_Demo_C* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Fish_Manager_C", "ScarePlayer");

	Params::BP_Fish_Manager_C_ScarePlayer Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Fish_Manager.BP_Fish_Manager_C.ExecuteUbergraph_BP_Fish_Manager
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Fish_Manager_C::ExecuteUbergraph_BP_Fish_Manager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Fish_Manager_C", "ExecuteUbergraph_BP_Fish_Manager");

	Params::BP_Fish_Manager_C_ExecuteUbergraph_BP_Fish_Manager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

