#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Fence_A1

#include "Basic.hpp"

#include "BP_Fence_A1_classes.hpp"
#include "BP_Fence_A1_parameters.hpp"


namespace SDK
{

// Function BP_Fence_A1.BP_Fence_A1_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Fence_A1_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Fence_A1_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

