#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Fish_Manager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Fish_Manager.BP_Fish_Manager_C
// 0x0020 (0x0240 - 0x0220)
class ABP_Fish_Manager_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Swim_Alpha_BFC1A10049999E6BB8D7C6B651F43EFC;       // 0x0230(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Swim__Direction_BFC1A10049999E6BB8D7C6B651F43EFC;  // 0x0234(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_235[0x3];                                      // 0x0235(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Swim;                                              // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SpawnFish(class ABPCharacter_Demo_C* Player, bool* CanSpawn, struct FVector* StartingLoc, struct FVector* FrontLocation);
	void Swim__FinishedFunc();
	void Swim__UpdateFunc();
	void Swim__Destroy__EventFunc();
	void ScarePlayer(class ABPCharacter_Demo_C* Player);
	void ExecuteUbergraph_BP_Fish_Manager(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Fish_Manager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Fish_Manager_C")
	}
	static class ABP_Fish_Manager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Fish_Manager_C>();
	}
};
DUMPER7_ASSERTS_ABP_Fish_Manager_C;

}

