#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FurnitureLamp

#include "Basic.hpp"

#include "BP_FurnitureLamp_classes.hpp"
#include "BP_FurnitureLamp_parameters.hpp"


namespace SDK
{

// Function BP_FurnitureLamp.BP_FurnitureLamp_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_FurnitureLamp_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FurnitureLamp_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

