#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FilingCabinets2

#include "Basic.hpp"

#include "BP_FilingCabinets2_classes.hpp"
#include "BP_FilingCabinets2_parameters.hpp"


namespace SDK
{

// Function BP_FilingCabinets2.BP_FilingCabinets2_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_FilingCabinets2_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FilingCabinets2_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

