#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Item_PlasticBall

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Item_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Item_PlasticBall.BP_Item_PlasticBall_C
// 0x0020 (0x0278 - 0x0258)
class ABP_Item_PlasticBall_C final : public ABP_Item_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Item_PlasticBall_C;              // 0x0258(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          CanUse;                                            // 0x0260(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_261[0x7];                                      // 0x0261(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMaterialInterface*>             BallMaterialArray;                                 // 0x0268(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_BP_Item_PlasticBall(int32 EntryPoint);
	void MC_Throw();
	void OnCompleted_50AF23E94A2E16360294B19962EBEFE8(class FName NotifyName);
	void OnBlendOut_50AF23E94A2E16360294B19962EBEFE8(class FName NotifyName);
	void OnInterrupted_50AF23E94A2E16360294B19962EBEFE8(class FName NotifyName);
	void OnNotifyBegin_50AF23E94A2E16360294B19962EBEFE8(class FName NotifyName);
	void OnNotifyEnd_50AF23E94A2E16360294B19962EBEFE8(class FName NotifyName);
	void OnCompleted_3D9D3E014D86EA789E80D5BE8C6A60DF(class FName NotifyName);
	void OnBlendOut_3D9D3E014D86EA789E80D5BE8C6A60DF(class FName NotifyName);
	void OnInterrupted_3D9D3E014D86EA789E80D5BE8C6A60DF(class FName NotifyName);
	void OnNotifyBegin_3D9D3E014D86EA789E80D5BE8C6A60DF(class FName NotifyName);
	void OnNotifyEnd_3D9D3E014D86EA789E80D5BE8C6A60DF(class FName NotifyName);
	void ReceiveBeginPlay();
	void UseItem();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Item_PlasticBall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Item_PlasticBall_C")
	}
	static class ABP_Item_PlasticBall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Item_PlasticBall_C>();
	}
};
DUMPER7_ASSERTS_ABP_Item_PlasticBall_C;

}

