#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Item_PlasticBall

#include "Basic.hpp"

#include "BP_Item_PlasticBall_classes.hpp"
#include "BP_Item_PlasticBall_parameters.hpp"


namespace SDK
{

// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.ExecuteUbergraph_BP_Item_PlasticBall
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::ExecuteUbergraph_BP_Item_PlasticBall(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "ExecuteUbergraph_BP_Item_PlasticBall");

	Params::BP_Item_PlasticBall_C_ExecuteUbergraph_BP_Item_PlasticBall Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.MC_Throw
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Item_PlasticBall_C::MC_Throw()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "MC_Throw");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.OnCompleted_50AF23E94A2E16360294B19962EBEFE8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::OnCompleted_50AF23E94A2E16360294B19962EBEFE8(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "OnCompleted_50AF23E94A2E16360294B19962EBEFE8");

	Params::BP_Item_PlasticBall_C_OnCompleted_50AF23E94A2E16360294B19962EBEFE8 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.OnBlendOut_50AF23E94A2E16360294B19962EBEFE8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::OnBlendOut_50AF23E94A2E16360294B19962EBEFE8(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "OnBlendOut_50AF23E94A2E16360294B19962EBEFE8");

	Params::BP_Item_PlasticBall_C_OnBlendOut_50AF23E94A2E16360294B19962EBEFE8 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.OnInterrupted_50AF23E94A2E16360294B19962EBEFE8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::OnInterrupted_50AF23E94A2E16360294B19962EBEFE8(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "OnInterrupted_50AF23E94A2E16360294B19962EBEFE8");

	Params::BP_Item_PlasticBall_C_OnInterrupted_50AF23E94A2E16360294B19962EBEFE8 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.OnNotifyBegin_50AF23E94A2E16360294B19962EBEFE8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::OnNotifyBegin_50AF23E94A2E16360294B19962EBEFE8(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "OnNotifyBegin_50AF23E94A2E16360294B19962EBEFE8");

	Params::BP_Item_PlasticBall_C_OnNotifyBegin_50AF23E94A2E16360294B19962EBEFE8 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.OnNotifyEnd_50AF23E94A2E16360294B19962EBEFE8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::OnNotifyEnd_50AF23E94A2E16360294B19962EBEFE8(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "OnNotifyEnd_50AF23E94A2E16360294B19962EBEFE8");

	Params::BP_Item_PlasticBall_C_OnNotifyEnd_50AF23E94A2E16360294B19962EBEFE8 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.OnCompleted_3D9D3E014D86EA789E80D5BE8C6A60DF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::OnCompleted_3D9D3E014D86EA789E80D5BE8C6A60DF(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "OnCompleted_3D9D3E014D86EA789E80D5BE8C6A60DF");

	Params::BP_Item_PlasticBall_C_OnCompleted_3D9D3E014D86EA789E80D5BE8C6A60DF Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.OnBlendOut_3D9D3E014D86EA789E80D5BE8C6A60DF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::OnBlendOut_3D9D3E014D86EA789E80D5BE8C6A60DF(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "OnBlendOut_3D9D3E014D86EA789E80D5BE8C6A60DF");

	Params::BP_Item_PlasticBall_C_OnBlendOut_3D9D3E014D86EA789E80D5BE8C6A60DF Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.OnInterrupted_3D9D3E014D86EA789E80D5BE8C6A60DF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::OnInterrupted_3D9D3E014D86EA789E80D5BE8C6A60DF(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "OnInterrupted_3D9D3E014D86EA789E80D5BE8C6A60DF");

	Params::BP_Item_PlasticBall_C_OnInterrupted_3D9D3E014D86EA789E80D5BE8C6A60DF Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.OnNotifyBegin_3D9D3E014D86EA789E80D5BE8C6A60DF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::OnNotifyBegin_3D9D3E014D86EA789E80D5BE8C6A60DF(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "OnNotifyBegin_3D9D3E014D86EA789E80D5BE8C6A60DF");

	Params::BP_Item_PlasticBall_C_OnNotifyBegin_3D9D3E014D86EA789E80D5BE8C6A60DF Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.OnNotifyEnd_3D9D3E014D86EA789E80D5BE8C6A60DF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Item_PlasticBall_C::OnNotifyEnd_3D9D3E014D86EA789E80D5BE8C6A60DF(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "OnNotifyEnd_3D9D3E014D86EA789E80D5BE8C6A60DF");

	Params::BP_Item_PlasticBall_C_OnNotifyEnd_3D9D3E014D86EA789E80D5BE8C6A60DF Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Item_PlasticBall_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Item_PlasticBall.BP_Item_PlasticBall_C.UseItem
// (BlueprintCallable, BlueprintEvent)

void ABP_Item_PlasticBall_C::UseItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Item_PlasticBall_C", "UseItem");

	UObject::ProcessEvent(Func, nullptr);
}

}

