#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemSpawnerAny

#include "Basic.hpp"

#include "BP_ItemSpawnerAny_classes.hpp"
#include "BP_ItemSpawnerAny_parameters.hpp"


namespace SDK
{

// Function BP_ItemSpawnerAny.BP_ItemSpawnerAny_C.GetItem
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ABP_SpawnerManager_C*             SpawnerManager                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName*                            Item_0                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ItemSpawnerAny_C::GetItem(class ABP_SpawnerManager_C* SpawnerManager, class FName* Item_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemSpawnerAny_C", "GetItem");

	Params::BP_ItemSpawnerAny_C_GetItem Parms{};

	Parms.SpawnerManager = SpawnerManager;

	UObject::ProcessEvent(Func, &Parms);

	if (Item_0 != nullptr)
		*Item_0 = Parms.Item_0;
}


// Function BP_ItemSpawnerAny.BP_ItemSpawnerAny_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ItemSpawnerAny_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemSpawnerAny_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ItemSpawnerAny.BP_ItemSpawnerAny_C.ExecuteUbergraph_BP_ItemSpawnerAny
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ItemSpawnerAny_C::ExecuteUbergraph_BP_ItemSpawnerAny(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemSpawnerAny_C", "ExecuteUbergraph_BP_ItemSpawnerAny");

	Params::BP_ItemSpawnerAny_C_ExecuteUbergraph_BP_ItemSpawnerAny Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

