#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Locker04

#include "Basic.hpp"

#include "BP_Locker04_classes.hpp"
#include "BP_Locker04_parameters.hpp"


namespace SDK
{

// Function BP_Locker04.BP_Locker04_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Locker04_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Locker04_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

