#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lamp_ceiling_round

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Lamp_ceiling_round.BP_Lamp_ceiling_round_C
// 0x0020 (0x0240 - 0x0220)
class BP_Lamp_ceiling_round::ABP_Lamp_ceiling_round_C final : public AActor
{
public:
	class USpotLightComponent*                    SpotLight;                                         // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Lamp_ceiling_round;                                // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          Lamp_On_;                                          // 0x0238(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Lamp_ceiling_round.BP_Lamp_ceiling_round_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Lamp_ceiling_round_C")
	}
	static class BP_Lamp_ceiling_round::ABP_Lamp_ceiling_round_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Lamp_ceiling_round::ABP_Lamp_ceiling_round_C>();
	}
};
DUMPER7_ASSERTS_BP_Lamp_ceiling_round__ABP_Lamp_ceiling_round_C;

}

