#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lamp_hanging_fluorescent

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Lamp_hanging_fluorescent.BP_Lamp_hanging_fluorescent_C
// 0x0020 (0x0240 - 0x0220)
class ABP_Lamp_hanging_fluorescent_C final : public AActor
{
public:
	class URectLightComponent*                    RectLight;                                         // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Lamp_hanging_fluorescent;                          // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          Lamp_On_;                                          // 0x0238(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Lamp_hanging_fluorescent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Lamp_hanging_fluorescent_C")
	}
	static class ABP_Lamp_hanging_fluorescent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Lamp_hanging_fluorescent_C>();
	}
};
DUMPER7_ASSERTS_ABP_Lamp_hanging_fluorescent_C;

}

