#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LM_Portal_windowsmall_0

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LM_Portal_windowsmall.BP_LM_Portal_windowsmall_C
// 0x0010 (0x0230 - 0x0220)
class BP_LM_Portal_windowsmall_0::ABP_LM_Portal_windowsmall_C final : public AActor
{
public:
	class UChildActorComponent*                   Lightmass_Portal;                                  // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_LM_Portal_windowsmall.BP_LM_Portal_windowsmall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LM_Portal_windowsmall_C")
	}
	static class BP_LM_Portal_windowsmall_0::ABP_LM_Portal_windowsmall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_LM_Portal_windowsmall_0::ABP_LM_Portal_windowsmall_C>();
	}
};
DUMPER7_ASSERTS_BP_LM_Portal_windowsmall_0__ABP_LM_Portal_windowsmall_C;

}

