#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lamp_ceiling_round_0

#include "Basic.hpp"

#include "BP_Lamp_ceiling_round_0_classes.hpp"


namespace SDK
{

// Function BP_Lamp_ceiling_round.BP_Lamp_ceiling_round_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void BP_Lamp_ceiling_round_0::ABP_Lamp_ceiling_round_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lamp_ceiling_round_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

