#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Locker03

#include "Basic.hpp"

#include "BP_Locker03_classes.hpp"
#include "BP_Locker03_parameters.hpp"


namespace SDK
{

// Function BP_Locker03.BP_Locker03_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Locker03_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Locker03_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

