#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OceanCheckpoint_Trigger

#include "Basic.hpp"

#include "BP_OceanCheckpoint_Trigger_classes.hpp"
#include "BP_OceanCheckpoint_Trigger_parameters.hpp"


namespace SDK
{

// Function BP_OceanCheckpoint_Trigger.BP_OceanCheckpoint_Trigger_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_OceanCheckpoint_Trigger_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_OceanCheckpoint_Trigger_C", "ReceiveActorBeginOverlap");

	Params::BP_OceanCheckpoint_Trigger_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_OceanCheckpoint_Trigger.BP_OceanCheckpoint_Trigger_C.ExecuteUbergraph_BP_OceanCheckpoint_Trigger
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_OceanCheckpoint_Trigger_C::ExecuteUbergraph_BP_OceanCheckpoint_Trigger(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_OceanCheckpoint_Trigger_C", "ExecuteUbergraph_BP_OceanCheckpoint_Trigger");

	Params::BP_OceanCheckpoint_Trigger_C_ExecuteUbergraph_BP_OceanCheckpoint_Trigger Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

