#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OceanCheckpoint_Trigger

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_OceanCheckpoint_Trigger.BP_OceanCheckpoint_Trigger_C
// 0x0010 (0x0238 - 0x0228)
class ABP_OceanCheckpoint_Trigger_C final : public ATriggerBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         Checkpoint;                                        // 0x0230(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ExecuteUbergraph_BP_OceanCheckpoint_Trigger(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_OceanCheckpoint_Trigger_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_OceanCheckpoint_Trigger_C")
	}
	static class ABP_OceanCheckpoint_Trigger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_OceanCheckpoint_Trigger_C>();
	}
};
DUMPER7_ASSERTS_ABP_OceanCheckpoint_Trigger_C;

}

