#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Stairs_main_R

#include "Basic.hpp"

#include "BP_Stairs_main_R_classes.hpp"


namespace SDK
{

// Function BP_Stairs_main_R.BP_Stairs_main_R_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Stairs_main_R_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Stairs_main_R_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

