#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Terrace_Roof_B1

#include "Basic.hpp"

#include "BP_Terrace_Roof_B1_classes.hpp"
#include "BP_Terrace_Roof_B1_parameters.hpp"


namespace SDK
{

// Function BP_Terrace_Roof_B1.BP_Terrace_Roof_B1_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Terrace_Roof_B1_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Terrace_Roof_B1_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

