#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VideoPlayerActor

#include "Basic.hpp"

#include "BP_VideoPlayerActor_classes.hpp"
#include "BP_VideoPlayerActor_parameters.hpp"


namespace SDK
{

// Function BP_VideoPlayerActor.BP_VideoPlayerActor_C.OnVideoEnded
// (Event, Protected, BlueprintEvent)

void ABP_VideoPlayerActor_C::OnVideoEnded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VideoPlayerActor_C", "OnVideoEnded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VideoPlayerActor.BP_VideoPlayerActor_C.OnVideoStarted
// (Event, Protected, BlueprintEvent)

void ABP_VideoPlayerActor_C::OnVideoStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VideoPlayerActor_C", "OnVideoStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VideoPlayerActor.BP_VideoPlayerActor_C.ExecuteUbergraph_BP_VideoPlayerActor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_VideoPlayerActor_C::ExecuteUbergraph_BP_VideoPlayerActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VideoPlayerActor_C", "ExecuteUbergraph_BP_VideoPlayerActor");

	Params::BP_VideoPlayerActor_C_ExecuteUbergraph_BP_VideoPlayerActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

