#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VideoPlayerActor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Backrooms_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VideoPlayerActor.BP_VideoPlayerActor_C
// 0x0050 (0x0310 - 0x02C0)
class ABP_VideoPlayerActor_C final : public AFancyVideoPlayer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         Volume;                                            // 0x02C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_2CC[0x4];                                      // 0x02CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             DialogueSound;                                     // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DialogueDelay;                                     // 0x02D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                DialogueOffset;                                    // 0x02DC(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   DialogueSubtitle;                                  // 0x02E8(0x0018)(Edit, BlueprintVisible)
	TMulticastInlineDelegate<void(bool IsPlayingCinematic)> OnCinematicUpdated;                      // 0x0300(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void OnVideoEnded();
	void OnVideoStarted();
	void ExecuteUbergraph_BP_VideoPlayerActor(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_VideoPlayerActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_VideoPlayerActor_C")
	}
	static class ABP_VideoPlayerActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_VideoPlayerActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_VideoPlayerActor_C;

}

