#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Workdesk_extension

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Workdesk_extension.BP_Workdesk_extension_C
// 0x0028 (0x0248 - 0x0220)
class ABP_Workdesk_extension_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Workdesk_drawer_A1;                                // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Workdesk_drawer_B;                                 // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Workdesk_drawer_A;                                 // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Workdesk_extension;                                // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Workdesk_extension_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Workdesk_extension_C")
	}
	static class ABP_Workdesk_extension_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Workdesk_extension_C>();
	}
};
DUMPER7_ASSERTS_ABP_Workdesk_extension_C;

}

