#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WallOut_0

#include "Basic.hpp"

#include "BP_WallOut_0_classes.hpp"
#include "BP_WallOut_0_parameters.hpp"


namespace SDK
{

// Function BP_WallOut.BP_WallOut_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void BP_WallOut_0::ABP_WallOut_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WallOut_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

