#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Wire01

#include "Basic.hpp"

#include "BP_Wire01_classes.hpp"
#include "BP_Wire01_parameters.hpp"


namespace SDK
{

// Function BP_Wire01.BP_Wire01_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Wire01_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Wire01_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

