#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Window

#include "Basic.hpp"

#include "BP_Window_classes.hpp"
#include "BP_Window_parameters.hpp"


namespace SDK
{

// Function BP_Window.BP_Window_C.ExecuteUbergraph_BP_Window
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Window_C::ExecuteUbergraph_BP_Window(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Window_C", "ExecuteUbergraph_BP_Window");

	Params::BP_Window_C_ExecuteUbergraph_BP_Window Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Window.BP_Window_C.OnUsedNotify
// (Event, Public, BlueprintEvent)

void ABP_Window_C::OnUsedNotify()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Window_C", "OnUsedNotify");

	UObject::ProcessEvent(Func, nullptr);
}

}

