#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Window_single_static

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Window_single_static.BP_Window_single_static_C
// 0x0018 (0x0238 - 0x0220)
class BP_Window_single_static::ABP_Window_single_static_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Windowglass_A_mesh;                                // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Window_single_static_mesh;                         // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_Window_single_static.BP_Window_single_static_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Window_single_static_C")
	}
	static class BP_Window_single_static::ABP_Window_single_static_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_Window_single_static::ABP_Window_single_static_C>();
	}
};
DUMPER7_ASSERTS_BP_Window_single_static__ABP_Window_single_static_C;

}

