#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WallIn

#include "Basic.hpp"

#include "E_WallIn_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_WallIn.BP_WallIn_C
// 0x0080 (0x02A0 - 0x0220)
class BP_WallIn::ABP_WallIn_C final : public AActor
{
public:
	class UStaticMeshComponent*                   Decal_corner_mesh;                                 // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   WallIn_mesh;                                       // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	E_WallIn::E_WallIn                            WallIn;                                            // 0x0238(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          WallIn_B;                                          // 0x0239(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Doorframe;                                         // 0x023A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Bent_Interior_Wall;                                // 0x023B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Decal_corner;                                      // 0x023C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Revert_Default_Materials;                          // 0x023D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_23E[0x2];                                      // 0x023E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UStaticMesh*>                    Wall_in_A_Meshes;                                  // 0x0240(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UStaticMesh*>                    Wall_in_A_Bent_Meshes;                             // 0x0250(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UStaticMesh*>                    Wall_in_B_Meshes;                                  // 0x0260(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UStaticMesh*>                    Wall_in_B_Bent_Meshes;                             // 0x0270(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UStaticMesh*>                    Decal_Corner_A_Meshes;                             // 0x0280(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UStaticMesh*>                    Decal_Corner_B_Meshes;                             // 0x0290(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass BP_WallIn.BP_WallIn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WallIn_C")
	}
	static class BP_WallIn::ABP_WallIn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BP_WallIn::ABP_WallIn_C>();
	}
};
DUMPER7_ASSERTS_BP_WallIn__ABP_WallIn_C;

}

