#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Window

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Backrooms_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Window.BP_Window_C
// 0x0010 (0x0258 - 0x0248)
class ABP_Window_C final : public AInteractableActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0248(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Windowglass_door_sliding;                          // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Window(int32 EntryPoint);
	void OnUsedNotify();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Window_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Window_C")
	}
	static class ABP_Window_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Window_C>();
	}
};
DUMPER7_ASSERTS_ABP_Window_C;

}

