#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WallIn

#include "Basic.hpp"

#include "BP_WallIn_classes.hpp"
#include "BP_WallIn_parameters.hpp"


namespace SDK
{

// Function BP_WallIn.BP_WallIn_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void BP_WallIn::ABP_WallIn_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WallIn_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

