#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_TelemetryUtilities

#include "Basic.hpp"

#include "BPFL_TelemetryUtilities_classes.hpp"
#include "BPFL_TelemetryUtilities_parameters.hpp"


namespace SDK
{

// Function BPFL_TelemetryUtilities.BPFL_TelemetryUtilities_C.SendDisconnectTelemetryEvent
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFancyPlayerDisconnectReason            DisconnectReason                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_TelemetryUtilities_C::SendDisconnectTelemetryEvent(EFancyPlayerDisconnectReason DisconnectReason, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_TelemetryUtilities_C", "SendDisconnectTelemetryEvent");

	Params::BPFL_TelemetryUtilities_C_SendDisconnectTelemetryEvent Parms{};

	Parms.DisconnectReason = DisconnectReason;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPFL_TelemetryUtilities.BPFL_TelemetryUtilities_C.SendQuitGameTelemetryEvent
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_TelemetryUtilities_C::SendQuitGameTelemetryEvent(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_TelemetryUtilities_C", "SendQuitGameTelemetryEvent");

	Params::BPFL_TelemetryUtilities_C_SendQuitGameTelemetryEvent Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPFL_TelemetryUtilities.BPFL_TelemetryUtilities_C.RefreshGameplayActivityTelemetryData
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerState*                     NewPlayerState                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_TelemetryUtilities_C::RefreshGameplayActivityTelemetryData(class APlayerState* NewPlayerState, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_TelemetryUtilities_C", "RefreshGameplayActivityTelemetryData");

	Params::BPFL_TelemetryUtilities_C_RefreshGameplayActivityTelemetryData Parms{};

	Parms.NewPlayerState = NewPlayerState;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}

}

