#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_TelemetryUtilities

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "Backrooms_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPFL_TelemetryUtilities.BPFL_TelemetryUtilities_C
// 0x0000 (0x0028 - 0x0028)
class UBPFL_TelemetryUtilities_C final : public UBlueprintFunctionLibrary
{
public:
	static void SendDisconnectTelemetryEvent(EFancyPlayerDisconnectReason DisconnectReason, class UObject* __WorldContext);
	static void SendQuitGameTelemetryEvent(class UObject* __WorldContext);
	static void RefreshGameplayActivityTelemetryData(class APlayerState* NewPlayerState, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPFL_TelemetryUtilities_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPFL_TelemetryUtilities_C")
	}
	static class UBPFL_TelemetryUtilities_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPFL_TelemetryUtilities_C>();
	}
};
DUMPER7_ASSERTS_UBPFL_TelemetryUtilities_C;

}

