#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CageScare

#include "Basic.hpp"

#include "CageScare_classes.hpp"
#include "CageScare_parameters.hpp"


namespace SDK
{

// Function CageScare.SequenceDirector_C.SequenceEvent__ENTRYPOINTSequenceDirector_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASkeletalMeshActor*               SK_AnglerFish                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void CageScare::USequenceDirector_C::SequenceEvent__ENTRYPOINTSequenceDirector_0(class ASkeletalMeshActor* SK_AnglerFish)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SequenceEvent__ENTRYPOINTSequenceDirector_0");

	Params::SequenceDirector_C_SequenceEvent__ENTRYPOINTSequenceDirector_0 Parms{};

	Parms.SK_AnglerFish = SK_AnglerFish;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CageScare.SequenceDirector_C.SK_AnglerFish_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASkeletalMeshActor*               SK_AnglerFish                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void CageScare::USequenceDirector_C::SK_AnglerFish_Event_0(class ASkeletalMeshActor* SK_AnglerFish)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "SK_AnglerFish_Event_0");

	Params::SequenceDirector_C_SK_AnglerFish_Event_0 Parms{};

	Parms.SK_AnglerFish = SK_AnglerFish;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CageScare.SequenceDirector_C.ExecuteUbergraph_SequenceDirector
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void CageScare::USequenceDirector_C::ExecuteUbergraph_SequenceDirector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SequenceDirector_C", "ExecuteUbergraph_SequenceDirector");

	Params::SequenceDirector_C_ExecuteUbergraph_SequenceDirector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

