#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_WallIn

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_WallIn.E_WallIn
// NumValues: 0x0014
enum class E_WallIn::E_WallIn : uint8
{
	NewEnumerator19                          = 0,
	NewEnumerator25                          = 1,
	NewEnumerator26                          = 2,
	NewEnumerator27                          = 3,
	NewEnumerator28                          = 4,
	NewEnumerator29                          = 5,
	NewEnumerator30                          = 6,
	NewEnumerator31                          = 7,
	NewEnumerator32                          = 8,
	NewEnumerator33                          = 9,
	NewEnumerator34                          = 10,
	NewEnumerator35                          = 11,
	NewEnumerator36                          = 12,
	NewEnumerator37                          = 13,
	NewEnumerator38                          = 14,
	NewEnumerator39                          = 15,
	NewEnumerator40                          = 16,
	NewEnumerator41                          = 17,
	NewEnumerator42                          = 18,
	E_MAX                                    = 19,
};

}

