#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_WallOut

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_WallOut.E_WallOut
// NumValues: 0x000F
enum class E_WallOut::E_WallOut : uint8
{
	NewEnumerator25                          = 0,
	NewEnumerator26                          = 1,
	NewEnumerator27                          = 2,
	NewEnumerator28                          = 3,
	NewEnumerator29                          = 4,
	NewEnumerator30                          = 5,
	NewEnumerator31                          = 6,
	NewEnumerator32                          = 7,
	NewEnumerator33                          = 8,
	NewEnumerator34                          = 9,
	NewEnumerator35                          = 10,
	NewEnumerator36                          = 11,
	NewEnumerator19                          = 12,
	NewEnumerator37                          = 13,
	E_MAX                                    = 14,
};

}

