#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: lazygodray_FX_BP

#include "Basic.hpp"

#include "lazygodray_FX_BP_classes.hpp"
#include "lazygodray_FX_BP_parameters.hpp"


namespace SDK
{

// Function lazygodray_FX_BP.lazygodray_FX_BP_C.ExecuteUbergraph_lazygodray_FX_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Alazygodray_FX_BP_C::ExecuteUbergraph_lazygodray_FX_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("lazygodray_FX_BP_C", "ExecuteUbergraph_lazygodray_FX_BP");

	Params::lazygodray_FX_BP_C_ExecuteUbergraph_lazygodray_FX_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function lazygodray_FX_BP.lazygodray_FX_BP_C.OnChangingGodrayParameters
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    UpdateSpotlight                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Alazygodray_FX_BP_C::OnChangingGodrayParameters(bool UpdateSpotlight)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("lazygodray_FX_BP_C", "OnChangingGodrayParameters");

	Params::lazygodray_FX_BP_C_OnChangingGodrayParameters Parms{};

	Parms.UpdateSpotlight = UpdateSpotlight;

	UObject::ProcessEvent(Func, &Parms);
}


// Function lazygodray_FX_BP.lazygodray_FX_BP_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Alazygodray_FX_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("lazygodray_FX_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

