#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lobby

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Lobby.Lobby_C
// 0x0008 (0x0230 - 0x0228)
class ALobby_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_Lobby(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Lobby_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Lobby_C")
	}
	static class ALobby_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALobby_C>();
	}
};
DUMPER7_ASSERTS_ALobby_C;

}

