#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MP_Thallasophobia

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MP_GameMode_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MP_Thallasophobia.MP_Thallasophobia_C
// 0x0008 (0x0398 - 0x0390)
class AMP_Thallasophobia_C final : public AMP_GameMode_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_MP_Thallasophobia_C;                // 0x0390(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	class AActor* ChoosePlayerStart(class AController* Player);
	void LoadCheckpoints();
	void OnPlayerSpawn(class ABPCharacter_Demo_C* Player);
	void ExecuteUbergraph_MP_Thallasophobia(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MP_Thallasophobia_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MP_Thallasophobia_C")
	}
	static class AMP_Thallasophobia_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMP_Thallasophobia_C>();
	}
};
DUMPER7_ASSERTS_AMP_Thallasophobia_C;

}

