#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OceanMap

#include "Basic.hpp"

#include "OceanMap_classes.hpp"
#include "OceanMap_parameters.hpp"


namespace SDK
{

// Function OceanMap.OceanMap_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AOceanMap_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OceanMap_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OceanMap.OceanMap_C.ExecuteUbergraph_OceanMap
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AOceanMap_C::ExecuteUbergraph_OceanMap(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OceanMap_C", "ExecuteUbergraph_OceanMap");

	Params::OceanMap_C_ExecuteUbergraph_OceanMap Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

