#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OceanMap

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass OceanMap.OceanMap_C
// 0x0008 (0x0230 - 0x0228)
class AOceanMap_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_OceanMap(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("OceanMap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OceanMap_C")
	}
	static class AOceanMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOceanMap_C>();
	}
};
DUMPER7_ASSERTS_AOceanMap_C;

}

