#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OceanHouse

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass OceanHouse.OceanHouse_C
// 0x0000 (0x0228 - 0x0228)
class AOceanHouse_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("OceanHouse_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OceanHouse_C")
	}
	static class AOceanHouse_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOceanHouse_C>();
	}
};
DUMPER7_ASSERTS_AOceanHouse_C;

}

