#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_FlowerRoomSaveData

#include "Basic.hpp"

#include "E_FlowerTYPE_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// UserDefinedStruct ST_FlowerRoomSaveData.ST_FlowerRoomSaveData
// 0x0014 (0x0014 - 0x0000)
struct FST_FlowerRoomSaveData final
{
public:
	E_FlowerType                                  FlowerType_9_0171B40F495A5256A56267A69B430AC6;     // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           FlowerColor_10_90E9322A43968A2B9B89128895772C8B;   // 0x0004(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FST_FlowerRoomSaveData;

}

