#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_ItemSpawnDT

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct ST_ItemSpawnDT.ST_ItemSpawnDT
// 0x0004 (0x0004 - 0x0000)
struct FST_ItemSpawnDT final
{
public:
	int32                                         SpawnChance_5_DC8D08C246730C2B4B5A7F91884A7B27;    // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FST_ItemSpawnDT;

}

