#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterVisiblityTrigger

#include "Basic.hpp"

#include "WaterVisiblityTrigger_classes.hpp"
#include "WaterVisiblityTrigger_parameters.hpp"


namespace SDK
{

// Function WaterVisiblityTrigger.WaterVisiblityTrigger_C.FishScare
// (Public, BlueprintCallable, BlueprintEvent)

void AWaterVisiblityTrigger_C::FishScare()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WaterVisiblityTrigger_C", "FishScare");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WaterVisiblityTrigger.WaterVisiblityTrigger_C.StopSinkingPlayers
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AWaterVisiblityTrigger_C::StopSinkingPlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WaterVisiblityTrigger_C", "StopSinkingPlayers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WaterVisiblityTrigger.WaterVisiblityTrigger_C.CheckAllPlayersUnderwater
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABPCharacter_Demo_C*              DivingPlayer                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Underwater                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AWaterVisiblityTrigger_C::CheckAllPlayersUnderwater(class ABPCharacter_Demo_C* DivingPlayer, bool* Underwater)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WaterVisiblityTrigger_C", "CheckAllPlayersUnderwater");

	Params::WaterVisiblityTrigger_C_CheckAllPlayersUnderwater Parms{};

	Parms.DivingPlayer = DivingPlayer;

	UObject::ProcessEvent(Func, &Parms);

	if (Underwater != nullptr)
		*Underwater = Parms.Underwater;
}


// Function WaterVisiblityTrigger.WaterVisiblityTrigger_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AWaterVisiblityTrigger_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WaterVisiblityTrigger_C", "ReceiveActorBeginOverlap");

	Params::WaterVisiblityTrigger_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WaterVisiblityTrigger.WaterVisiblityTrigger_C.ExecuteUbergraph_WaterVisiblityTrigger
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AWaterVisiblityTrigger_C::ExecuteUbergraph_WaterVisiblityTrigger(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WaterVisiblityTrigger_C", "ExecuteUbergraph_WaterVisiblityTrigger");

	Params::WaterVisiblityTrigger_C_ExecuteUbergraph_WaterVisiblityTrigger Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

