#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterVisiblityTrigger

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WaterVisiblityTrigger.WaterVisiblityTrigger_C
// 0x0018 (0x0240 - 0x0228)
class AWaterVisiblityTrigger_C final : public ATriggerBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AEight_FFT_H_Ocean_Sim_C*               Water;                                             // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Fish_Manager_C*                     FishManager;                                       // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void FishScare();
	void StopSinkingPlayers();
	void CheckAllPlayersUnderwater(class ABPCharacter_Demo_C* DivingPlayer, bool* Underwater);
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ExecuteUbergraph_WaterVisiblityTrigger(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WaterVisiblityTrigger_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WaterVisiblityTrigger_C")
	}
	static class AWaterVisiblityTrigger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWaterVisiblityTrigger_C>();
	}
};
DUMPER7_ASSERTS_AWaterVisiblityTrigger_C;

}

