#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_VideoPlayer

#include "Basic.hpp"

#include "WB_VideoPlayer_classes.hpp"
#include "WB_VideoPlayer_parameters.hpp"


namespace SDK
{

// Function WB_VideoPlayer.WB_VideoPlayer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWB_VideoPlayer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_VideoPlayer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_VideoPlayer.WB_VideoPlayer_C.UpdateSkipText
// (BlueprintCallable, BlueprintEvent)

void UWB_VideoPlayer_C::UpdateSkipText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_VideoPlayer_C", "UpdateSkipText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_VideoPlayer.WB_VideoPlayer_C.OnVoteChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVoteData&                 VoteData                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UWB_VideoPlayer_C::OnVoteChanged(const struct FVoteData& VoteData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_VideoPlayer_C", "OnVoteChanged");

	Params::WB_VideoPlayer_C_OnVoteChanged Parms{};

	Parms.VoteData = std::move(VoteData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_VideoPlayer.WB_VideoPlayer_C.OnVoteStarted
// (BlueprintCallable, BlueprintEvent)

void UWB_VideoPlayer_C::OnVoteStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_VideoPlayer_C", "OnVoteStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_VideoPlayer.WB_VideoPlayer_C.FadeOut
// (BlueprintCallable, BlueprintEvent)

void UWB_VideoPlayer_C::FadeOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_VideoPlayer_C", "FadeOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_VideoPlayer.WB_VideoPlayer_C.ExecuteUbergraph_WB_VideoPlayer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_VideoPlayer_C::ExecuteUbergraph_WB_VideoPlayer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_VideoPlayer_C", "ExecuteUbergraph_WB_VideoPlayer");

	Params::WB_VideoPlayer_C_ExecuteUbergraph_WB_VideoPlayer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

